import type { Metadata } from 'next'
import { Be_Vietnam_Pro as FontSans } from 'next/font/google'

import { GetMe } from '@core/components/get-me'
import { default as StyleProvider } from '@core/libs/antd/Provider'
import { QueryProvider } from '@core/libs/react-query'
import { StoreProvider } from '@core/libs/zustands'

import '@core/styles/globals.css'

const fontSans = FontSans({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['vietnamese'],
})

export const metadata: Metadata = {
  title: 'Lunas CRM',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <StyleProvider>
          <QueryProvider>
            <StoreProvider>
              <GetMe />
              {children}
            </StoreProvider>
          </QueryProvider>
        </StyleProvider>
      </body>
    </html>
  )
}
